source 'https://github.com/lingdf/FFSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'FFAPIs_Example' do
  pod 'FFAPIs', :path => '../'

  target 'FFAPIs_Tests' do
    inherit! :search_paths

    
  end
end
